name: dart_metrics_app
description: "DART 공시 기반 주식 지표 분석 앱"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  http: ^1.2.0
  fl_chart: ^0.69.0
  shared_preferences: ^2.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.14.1
  flutter_native_splash: ^2.4.1

flutter:
  uses-material-design: true

flutter_launcher_icons:
  android: "launcher_icon"
  ios: false
  image_path: "assets/icon/app_icon.png"
  min_sdk_android: 21
  adaptive_icon_background: "#1976D2"  # 파란색
  adaptive_icon_foreground: "assets/icon/app_icon.png"
  
flutter_native_splash:
  color: "#1976D2"   # 파란 배경
  image: "assets/icon/app_icon.png"
  android_12:
    color: "#1976D2"
    image: "assets/icon/app_icon.png"